environment: staging

apps:
  api:
    deployment:
      repository: registry.digitalocean.com/paralect/ship-api
      replicas: 1
      livenessProbe:
        path: /health
        port: 3001
        initialDelaySeconds: 6000
        periodSeconds: 12000
      imagePullPolicy: Always
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-app
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 3001
          protocol: TCP
    services:
      - name: api
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 3001
        ingress:
          host: api.paralect.net
          secretName: letsencrypt-api
        selector:
          app: api
      - name: socket
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 8082
        ingress:
          host: socket.paralect.net
          secretName: letsencrypt-socket
        selector:
          app: api

  web:
    deployment:
      repository: registry.digitalocean.com/paralect/ship-web
      replicas: 1
      livenessProbe:
        path: /
        port: 80
        initialDelaySeconds: 3
        periodSeconds: 5
      imagePullPolicy: Always
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-app
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 80
          protocol: TCP
    services:
      - name: web
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
        ingress:
          host: app.paralect.net
          secretName: letsencrypt-web
        selector:
          app: web

  landing:
    deployment:
      repository: registry.digitalocean.com/paralect/ship-landing
      replicas: 1
      livenessProbe:
        path: /health
        port: 3000
        initialDelaySeconds: 3
        periodSeconds: 5
      imagePullPolicy: Always
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 3000
          protocol: TCP
    services:
      - name: landing
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 3000
        ingress:
          host: landing.paralect.net
          secretName: letsencrypt-landing
        selector:
          app: landing

  admin:
    deployment:
      repository: registry.digitalocean.com/paralect/ship-admin
      replicas: 1
      livenessProbe:
        path: /health
        port: 3003
        initialDelaySeconds: 3
        periodSeconds: 5
      imagePullPolicy: Always
      env:
        - name: APP_ENV
          value: "staging"
      ports:
        - containerPort: 3003
          protocol: TCP
    services:
      - name: admin
        type: ClusterIP
        ports:
          - protocol: TCP
            port: 80
            targetPort: 3003
        ingress:
          host: admin.paralect.net
          secretName: letsencrypt-admin
        selector:
          app: admin

imageCredentials:
  enabled: true
  secretName: regcred
