apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  acme:
    server: {{ .Values.server }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.name }}
    solvers:
      - http01:
          ingress:
            class: nginx
