service:
  type: ClusterIP

sourceControl:
  provider: github

server:
  host: ci.paralect.net
  kubernetes:
    enabled: false
  protocol: https
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-drone

ingress:
  enabled: true
  hosts:
    - ci.paralect.net
  tls:
    - hosts:
        - ci.paralect.net
      secretName: letsencrypt
  annotations:
    kubernetes.io/ingress.class: "nginx"
    customHttpErrors: "404,502"
    nginx.ingress.kubernetes.io/default-backend: error-pages
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"

agent:
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
  volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-drone
