kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: web
        image: registry.digitalocean.com/paralect/ship-web:{{ .Values.imagesVersion }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: APP_ENV
          value: {{ .Values.environment }}
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
