name: api
on:
  push:
    branches: [ main, production ]
    paths:
      - 'api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env vars (staging)
        if: endsWith(github.ref, '/main')
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_STAGING }}" >> $GITHUB_ENV
      - name: Set env vars (production)
        if: endsWith(github.ref, '/production')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_PRODUCTION }}" >> $GITHUB_ENV
      - name: Build api
        id: build-app
        run: |
          docker build -f deploy/script/Dockerfile -t deploy ./
          docker run -v /var/run/docker.sock:/var/run/docker.sock:rw \
          -e AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_REGION="${{ secrets.AWS_REGION }}" \
          -e AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          -e CLUSTER_NAME=${{ env.CLUSTER_NAME }} \
          -e SERVICE=api \
          -e IMAGE_TAG=${{ env.ENVIRONMENT }}.${{ github.sha }} \
          -e NAMESPACE=${{ env.ENVIRONMENT }} \
          -e ENVIRONMENT=${{ env.ENVIRONMENT }} \
          deploy
