#Adding Grafana repository
helm repo add grafana https://grafana.github.io/helm-charts

#Updating Helm
helm repo update

kubectl create ns monitoring

# This create persistent storage for grafana and prometheus
kubectl apply -n monitoring -f ./configs/pv-grafana.yml
kubectl apply -n monitoring -f ./configs/pv-prometheus.yml
kubectl apply -n monitoring -f ./configs/pvc-grafana.yml
kubectl apply -n monitoring -f ./configs/pvc-prometheus.yml

# Main install script
helm upgrade --install loki-stack --namespace monitoring grafana/loki-stack  --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false -f values.yml

# For exposing Grafana to the domain
kubectl apply -n monitoring -f ./configs/loki-stack-grafana-ingress.yml

# For getting Grafana password
# This might be autogenerated when Grafana is stateless
kubectl get secret --namespace monitoring loki-stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo